# Generated by Django 3.0.8 on 2022-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_capacity', models.CharField(max_length=500)),
                ('room_discription', models.CharField(max_length=500)),
                ('facilities', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/room')),
            ],
        ),
    ]
