# Generated by Django 3.0.8 on 2022-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_date_time', models.DateField()),
                ('to_date_time', models.DateField()),
                ('mobile', models.IntegerField()),
                ('total_bill', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
            ],
        ),
    ]
