# Generated by Django 3.0.8 on 2022-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_book_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_book',
            name='from_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room_book',
            name='to_date_time',
            field=models.DateTimeField(),
        ),
    ]
