# Generated by Django 3.0.8 on 2022-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/product/images')),
                ('unit', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
