# Generated by Django 3.0.8 on 2022-05-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('online', 'Online'), ('cash on delivery', 'Cash on delivery')], max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsds', to='store.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kjdjis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
