# Generated by Django 3.0.8 on 2022-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_placeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis',
            field=models.CharField(default='sdsd', max_length=500),
            preserve_default=False,
        ),
    ]
