# Generated by Django 3.0.8 on 2022-05-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
