# Generated by Django 3.0.8 on 2022-05-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product_unit'),
            preserve_default=False,
        ),
    ]
