# Generated by Django 3.0.8 on 2022-05-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='placeorder',
        ),
    ]
