# Generated by Django 3.0.8 on 2022-05-15 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20220515_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('online', 'Online'), ('cash on delivery', 'Cash on delivery')], max_length=100)),
                ('status', models.CharField(choices=[('recived', 'Recived'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('out for delievry', 'Out for delievry'), ('accepted', 'Deliverd'), ('cancled', 'Cancled')], max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsds', to='account.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kjdjis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
