# Generated by Django 3.0.8 on 2022-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('mobile_no', models.IntegerField()),
                ('service', models.CharField(choices=[('Preparations only', 'Preparations only'), ('Preparations/Transportation', 'Preparations/Transportation'), ('Preparation/Transportation/Staff', 'Preparation/Transportation/Staff')], max_length=100)),
            ],
        ),
    ]
