# Generated by Django 3.0.8 on 2022-05-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caters',
            new_name='caterers',
        ),
    ]
